### ISSUE TITLE
New unrar versions use different date format

### ISSUE THREAD

**Issue by WebSpider** [kyegupov/py-unrar2#14]
Hi,

Over at SiCKRAGETV/SickRage we're using py-unrar2 to postprocess media files.

Users have been reporting errors when switching to v5.30 of unrar, because apparently unrar has changed output of file dates, causing unrar2/unix.py, line 179 to fail parsing the file dates.

We have an open bug on this at SiCKRAGETV/sickrage-issues#2613 with relevant Tracebacks, user versions, Linux distro's and exact packages used.

**Comment by miigotu** [comment]
@yk4ever if the try/except is an ok solution for you I can PR. Not sure if that is the best route, just needed something to make it work in the mean time regardless of which unrar is installed.
